// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'es'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	localeSwitcher: {
		/**
		 * S​e​l​e​c​t​ ​l​a​n​g​u​a​g​e
		 */
		description: string
	}
	searchForm: {
		/**
		 * S​e​a​r​c​h
		 */
		inputLabel: string
		/**
		 * S​e​e​ ​a​l​l​ ​r​e​s​u​l​t​s
		 */
		buttonLabel: string
		/**
		 * S​u​g​g​e​s​t​i​o​n​s
		 */
		suggestionsLabel: string
		/**
		 * W​a​i​t​i​n​g​ ​f​o​r​ ​s​u​g​g​e​s​t​i​o​n​s​.​.​.
		 */
		loading: string
		/**
		 * N​o​ ​s​u​g​g​e​s​t​i​o​n​s​ ​f​o​r​ ​“​{​q​u​e​r​y​}​”
		 * @param {unknown} query
		 */
		empty: RequiredParams<'query'>
	}
	themeSelect: {
		/**
		 * L​i​g​h​t
		 */
		light: string
		/**
		 * D​a​r​k
		 */
		dark: string
		/**
		 * S​y​s​t​e​m
		 */
		system: string
	}
	postCard: {
		/**
		 * {​0​|​s​h​o​r​t​D​a​t​e​}
		 * @param {unknown} 0
		 */
		date: RequiredParams<'0|shortDate'>
	}
}

export type TranslationFunctions = {
	localeSwitcher: {
		/**
		 * Select language
		 */
		description: () => LocalizedString
	}
	searchForm: {
		/**
		 * Search
		 */
		inputLabel: () => LocalizedString
		/**
		 * See all results
		 */
		buttonLabel: () => LocalizedString
		/**
		 * Suggestions
		 */
		suggestionsLabel: () => LocalizedString
		/**
		 * Waiting for suggestions...
		 */
		loading: () => LocalizedString
		/**
		 * No suggestions for “{query}”
		 */
		empty: (arg: { query: unknown }) => LocalizedString
	}
	themeSelect: {
		/**
		 * Light
		 */
		light: () => LocalizedString
		/**
		 * Dark
		 */
		dark: () => LocalizedString
		/**
		 * System
		 */
		system: () => LocalizedString
	}
	postCard: {
		/**
		 * {0|shortDate}
		 */
		date: (arg0: unknown) => LocalizedString
	}
}

export type Formatters = {
	shortDate: (value: unknown) => unknown
}
