// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'es'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * Hi {name}!
	 * @param {unknown} name
	 */
	hi: RequiredParams<'name'>
	localeSwitcher: {
		/**
		 * Select language
		 */
		description: string
	}
	searchForm: {
		/**
		 * Search
		 */
		inputLabel: string
		/**
		 * See all results
		 */
		buttonLabel: string
		/**
		 * Suggestions
		 */
		suggestionsLabel: string
		/**
		 * Waiting for suggestions...
		 */
		loading: string
		/**
		 * No suggestions for “{query}”
		 * @param {unknown} query
		 */
		empty: RequiredParams<'query'>
	}
}

export type TranslationFunctions = {
	/**
	 * Hi {name}!
	 */
	hi: (arg: { name: unknown }) => LocalizedString
	localeSwitcher: {
		/**
		 * Select language
		 */
		description: () => LocalizedString
	}
	searchForm: {
		/**
		 * Search
		 */
		inputLabel: () => LocalizedString
		/**
		 * See all results
		 */
		buttonLabel: () => LocalizedString
		/**
		 * Suggestions
		 */
		suggestionsLabel: () => LocalizedString
		/**
		 * Waiting for suggestions...
		 */
		loading: () => LocalizedString
		/**
		 * No suggestions for “{query}”
		 */
		empty: (arg: { query: unknown }) => LocalizedString
	}
}

export type Formatters = {}
