backend:
  name: git-gateway
  branch: main
i18n:
  structure: multiple_folders
  locales: [en, es]
  default_locale: en
media_folder: "assets/uploads"
collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    i18n: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          default: "layouts/default.njk",
          i18n: duplicate,
        }
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          i18n: duplicate,
        }
      - {
          label: "Featured Image",
          name: "thumbnail",
          widget: "image",
          i18n: duplicate,
        }
      - { label: "Body", name: "body", widget: "markdown" }
